# Week 1 homework


## Imports

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## Load data and check them

In [75]:
housing_df = pd.read_csv('housing.csv')

In [76]:
housing_df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

## 1. What's the version of Pandas that you installed?

In [77]:
pd.__version__

'1.5.3'

## 2. How many columns are in the dataset?

In [78]:
housing_df.shape[1]

10

## 3. Which columns in the dataset have missing values?

In [79]:
housing_df.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

## 4. How many unique values does the ocean_proximity column have?

In [11]:
housing_df['ocean_proximity'].nunique()

5

## 5. What's the average value of the median_house_value for the houses located near the bay?

In [80]:
housing_df['median_house_value'].groupby(housing_df['ocean_proximity']).mean()

ocean_proximity
<1H OCEAN     240084.285464
INLAND        124805.392001
ISLAND        380440.000000
NEAR BAY      259212.311790
NEAR OCEAN    249433.977427
Name: median_house_value, dtype: float64

## 6.

### 6.1. Calculate the average of total_bedrooms column in the dataset.

In [16]:
mean_total_bedrooms = housing_df['total_bedrooms'].mean()
mean_total_bedrooms

537.8705525375618

### 6.2. Use the fillna method to fill the missing values in total_bedrooms with the mean value from the previous step.

In [17]:
housing_df['total_bedrooms'] = housing_df['total_bedrooms'].fillna(mean_total_bedrooms)

In [18]:
# Check
housing_df.isnull().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
ocean_proximity       0
dtype: int64

### 6.3. Now, calculate the average of total_bedrooms again.

In [81]:
new_mean_total_bedrooms = housing_df['total_bedrooms'].mean()

### 6.4. Has it changed?

In [82]:
new_mean_total_bedrooms == mean_total_bedrooms

True

## 7. 

### 7.1. Select all the options located on islands.

In [60]:
housing_df_island = housing_df[housing_df['ocean_proximity'] == "ISLAND"]

### 7.2. Select only columns housing_median_age, total_rooms, total_bedrooms.

In [83]:
housing_df_island = housing_df_island[['housing_median_age', 'total_rooms', 'total_bedrooms']]

In [63]:
# Check
housing_df_island.head()

housing_median_age  total_rooms  total_bedrooms
8314                27.0       1675.0           521.0
8315                52.0       2359.0           591.0
8316                52.0       2127.0           512.0
8317                52.0        996.0           264.0
8318                29.0        716.0           214.0

### 7.3. Get the underlying NumPy array. Let's call it X.

In [110]:
X = housing_df_island.to_numpy()

In [111]:
X

array([[  27., 1675.,  521.],
       [  52., 2359.,  591.],
       [  52., 2127.,  512.],
       [  52.,  996.,  264.],
       [  29.,  716.,  214.]])

### 7.4. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.

In [113]:
XTX = X.T @ X

In [114]:
XTX

array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

### 7.5. Compute the inverse of XTX.

In [115]:
XTX_inv = np.linalg.inv(XTX)

In [116]:
XTX_inv

array([[ 9.19403586e-04, -3.66412216e-05,  5.43072261e-05],
       [-3.66412216e-05,  8.23303633e-06, -2.77534485e-05],
       [ 5.43072261e-05, -2.77534485e-05,  1.00891325e-04]])

### 7.6. Create an array y with values [950, 1300, 800, 1000, 1300].

In [107]:
y = [950, 1300, 800, 1000, 1300]

### 7.7. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.

In [117]:
w = (XTX_inv.dot(X.T)).dot(y)

In [118]:
w

array([23.12330961, -1.48124183,  5.69922946])

### 7.8. What's the value of the last element of w?

In [119]:
w[-1]

5.6992294550655656